[package]
name = "gpt-text-read"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.8"
fltk = { version = "1", features = ["fltk-bundled"] }